## Introduction
The brief: The client is generally a low-cost retailer, offering many promotions and discounts. We will need to focus on such keywords. We will also need to move away from luxury keywords and topics, as we are targeting price-sensitive customers. Because we are going to be tight on budget, it would be good to focus on a tightly targeted set of keywords and make sure they are all set to exact and phrase match.

In [5]:
from pprint import pprint
import pandas as pd

In [6]:
words = ['buy','price','purchase','cost',
         'discount', 'buy online','shop online', 
         'cheap', 'best price', 'lowest price',
         'cheapest', 'best value', 'offers',
         'sale', 'bargain', 'affordable',
         ]

In [7]:
for word in words:
    print(word)

buy
price
purchase
cost
discount
buy online
shop online
cheap
best price
lowest price
cheapest
best value
offers
sale
bargain
affordable

##  Combine the words with the product names
To combine them with the product names to generate meaningful search keywords.

In [8]:
keywords_list=[]
products=['heels','boots','flip-flop','sports shoes','slipper','sandals','flats','snowshoes','sneaker','platformshoe','knee-high boots','stiletto']

for product in products:
    for word in words:
        keywords_list.append([product,word+' '+product])
        
pprint(keywords_list)

[['heels', 'buy heels'],
 ['heels', 'price heels'],
 ['heels', 'purchase heels'],
 ['heels', 'cost heels'],
 ['heels', 'discount heels'],
 ['heels', 'buy online heels'],
 ['heels', 'shop online heels'],
 ['heels', 'cheap heels'],
 ['heels', 'best price heels'],
 ['heels', 'lowest price heels'],
 ['heels', 'cheapest heels'],
 ['heels', 'best value heels'],
 ['heels', 'offers heels'],
 ['heels', 'sale heels'],
 ['heels', 'bargain heels'],
 ['heels', 'affordable heels'],
 ['boots', 'buy boots'],
 ['boots', 'price boots'],
 ['boots', 'purchase boots'],
 ['boots', 'cost boots'],
 ['boots', 'discount boots'],
 ['boots', 'buy online boots'],
 ['boots', 'shop online boots'],
 ['boots', 'cheap boots'],
 ['boots', 'best price boots'],
 ['boots', 'lowest price boots'],
 ['boots', 'cheapest boots'],
 ['boots', 'best value boots'],
 ['boots', 'offers boots'],
 ['boots', 'sale boots'],
 ['boots', 'bargain boots'],
 ['boots', 'affordable boots'],
 ['flip-flop', 'buy flip-flop'],
 ['flip-flop', 'price flip-flop'],
 ['flip-flop', 'purchase flip-flop'],
 ['flip-flop', 'cost flip-flop'],
 ['flip-flop', 'discount flip-flop'],
 ['flip-flop', 'buy online flip-flop'],
 ['flip-flop', 'shop online flip-flop'],
 ['flip-flop', 'cheap flip-flop'],
 ['flip-flop', 'best price flip-flop'],
 ['flip-flop', 'lowest price flip-flop'],
 ['flip-flop', 'cheapest flip-flop'],
 ['flip-flop', 'best value flip-flop'],
 ['flip-flop', 'offers flip-flop'],
 ['flip-flop', 'sale flip-flop'],
 ['flip-flop', 'bargain flip-flop'],
 ['flip-flop', 'affordable flip-flop'],
 ['sports shoes', 'buy sports shoes'],
 ['sports shoes', 'price sports shoes'],
 ['sports shoes', 'purchase sports shoes'],
 ['sports shoes', 'cost sports shoes'],
 ['sports shoes', 'discount sports shoes'],
 ['sports shoes', 'buy online sports shoes'],
 ['sports shoes', 'shop online sports shoes'],
 ['sports shoes', 'cheap sports shoes'],
 ['sports shoes', 'best price sports shoes'],
 ['sports shoes', 'lowest price sports shoes'],
 ['sports shoes', 'cheapest sports shoes'],
 ['sports shoes', 'best value sports shoes'],
 ['sports shoes', 'offers sports shoes'],
 ['sports shoes', 'sale sports shoes'],
 ['sports shoes', 'bargain sports shoes'],
 ['sports shoes', 'affordable sports shoes'],
 ['slipper', 'buy slipper'],
 ['slipper', 'price slipper'],
 ['slipper', 'purchase slipper'],
 ['slipper', 'cost slipper'],
 ['slipper', 'discount slipper'],
 ['slipper', 'buy online slipper'],
 ['slipper', 'shop online slipper'],
 ['slipper', 'cheap slipper'],
 ['slipper', 'best price slipper'],
 ['slipper', 'lowest price slipper'],
 ['slipper', 'cheapest slipper'],
 ['slipper', 'best value slipper'],
 ['slipper', 'offers slipper'],
 ['slipper', 'sale slipper'],
 ['slipper', 'bargain slipper'],
 ['slipper', 'affordable slipper'],
 ['sandals', 'buy sandals'],
 ['sandals', 'price sandals'],
 ['sandals', 'purchase sandals'],
 ['sandals', 'cost sandals'],
 ['sandals', 'discount sandals'],
 ['sandals', 'buy online sandals'],
 ['sandals', 'shop online sandals'],
 ['sandals', 'cheap sandals'],
 ['sandals', 'best price sandals'],
 ['sandals', 'lowest price sandals'],
 ['sandals', 'cheapest sandals'],
 ['sandals', 'best value sandals'],
 ['sandals', 'offers sandals'],
 ['sandals', 'sale sandals'],
 ['sandals', 'bargain sandals'],
 ['sandals', 'affordable sandals'],
 ['flats', 'buy flats'],
 ['flats', 'price flats'],
 ['flats', 'purchase flats'],
 ['flats', 'cost flats'],
 ['flats', 'discount flats'],
 ['flats', 'buy online flats'],
 ['flats', 'shop online flats'],
 ['flats', 'cheap flats'],
 ['flats', 'best price flats'],
 ['flats', 'lowest price flats'],
 ['flats', 'cheapest flats'],
 ['flats', 'best value flats'],
 ['flats', 'offers flats'],
 ['flats', 'sale flats'],
 ['flats', 'bargain flats'],
 ['flats', 'affordable flats'],
 ['snowshoes', 'buy snowshoes'],
 ['snowshoes', 'price snowshoes'],
 ['snowshoes', 'purchase snowshoes'],
 ['snowshoes', 'cost snowshoes'],
 ['snowshoes', 'discount snowshoes'],
 ['snowshoes', 'buy online snowshoes'],
 ['snowshoes', 'shop online snowshoes'],
 ['snowshoes', 'cheap snowshoes'],
 ['snowshoes', 'best price snowshoes'],
 ['snowshoes', 'lowest price snowshoes'],
 ['snowshoes', 'cheapest snowshoes'],
 ['snowshoes', 'best value snowshoes'],
 ['snowshoes', 'offers snowshoes'],
 ['snowshoes', 'sale snowshoes'],
 ['snowshoes', 'bargain snowshoes'],
 ['snowshoes', 'affordable snowshoes'],
 ['sneaker', 'buy sneaker'],
 ['sneaker', 'price sneaker'],
 ['sneaker', 'purchase sneaker'],
 ['sneaker', 'cost sneaker'],
 ['sneaker', 'discount sneaker'],
 ['sneaker', 'buy online sneaker'],
 ['sneaker', 'shop online sneaker'],
 ['sneaker', 'cheap sneaker'],
 ['sneaker', 'best price sneaker'],
 ['sneaker', 'lowest price sneaker'],
 ['sneaker', 'cheapest sneaker'],
 ['sneaker', 'best value sneaker'],
 ['sneaker', 'offers sneaker'],
 ['sneaker', 'sale sneaker'],
 ['sneaker', 'bargain sneaker'],
 ['sneaker', 'affordable sneaker'],
 ['platformshoe', 'buy platformshoe'],
 ['platformshoe', 'price platformshoe'],
 ['platformshoe', 'purchase platformshoe'],
 ['platformshoe', 'cost platformshoe'],
 ['platformshoe', 'discount platformshoe'],
 ['platformshoe', 'buy online platformshoe'],
 ['platformshoe', 'shop online platformshoe'],
 ['platformshoe', 'cheap platformshoe'],
 ['platformshoe', 'best price platformshoe'],
 ['platformshoe', 'lowest price platformshoe'],
 ['platformshoe', 'cheapest platformshoe'],
 ['platformshoe', 'best value platformshoe'],
 ['platformshoe', 'offers platformshoe'],
 ['platformshoe', 'sale platformshoe'],
 ['platformshoe', 'bargain platformshoe'],
 ['platformshoe', 'affordable platformshoe'],
 ['knee-high boots', 'buy knee-high boots'],
 ['knee-high boots', 'price knee-high boots'],
 ['knee-high boots', 'purchase knee-high boots'],
 ['knee-high boots', 'cost knee-high boots'],
 ['knee-high boots', 'discount knee-high boots'],
 ['knee-high boots', 'buy online knee-high boots'],
 ['knee-high boots', 'shop online knee-high boots'],
 ['knee-high boots', 'cheap knee-high boots'],
 ['knee-high boots', 'best price knee-high boots'],
 ['knee-high boots', 'lowest price knee-high boots'],
 ['knee-high boots', 'cheapest knee-high boots'],
 ['knee-high boots', 'best value knee-high boots'],
 ['knee-high boots', 'offers knee-high boots'],
 ['knee-high boots', 'sale knee-high boots'],
 ['knee-high boots', 'bargain knee-high boots'],
 ['knee-high boots', 'affordable knee-high boots'],
 ['stiletto', 'buy stiletto'],
 ['stiletto', 'price stiletto'],
 ['stiletto', 'purchase stiletto'],
 ['stiletto', 'cost stiletto'],
 ['stiletto', 'discount stiletto'],
 ['stiletto', 'buy online stiletto'],
 ['stiletto', 'shop online stiletto'],
 ['stiletto', 'cheap stiletto'],
 ['stiletto', 'best price stiletto'],
 ['stiletto', 'lowest price stiletto'],
 ['stiletto', 'cheapest stiletto'],
 ['stiletto', 'best value stiletto'],
 ['stiletto', 'offers stiletto'],
 ['stiletto', 'sale stiletto'],
 ['stiletto', 'bargain stiletto'],
 ['stiletto', 'affordable stiletto']]

## Convert the list of lists into a DataFrame
<p>Now we want to convert this list of lists into a DataFrame so we can easily manipulate it and manage the final output.</p>

In [9]:
keywords_df=pd.DataFrame.from_records(keywords_list)

In [10]:
keywords_df

            0                    1
0       heels            buy heels
1       heels          price heels
2       heels       purchase heels
3       heels           cost heels
4       heels       discount heels
..        ...                  ...
187  stiletto  best value stiletto
188  stiletto      offers stiletto
189  stiletto        sale stiletto
190  stiletto     bargain stiletto
191  stiletto  affordable stiletto

[192 rows x 2 columns]

## Rename the columns of the DataFrame
Before we can upload this table of keywords, we will need to give the columns meaningful names. 
If we inspect the DataFrame we just created above, we can see that the columns are currently named 
<code>0</code> and <code>1</code>.

In [11]:
keywords_df= keywords_df.rename(columns = {0:"Ad Group",1:"Keyword"})
keywords_df

     Ad Group              Keyword
0       heels            buy heels
1       heels          price heels
2       heels       purchase heels
3       heels           cost heels
4       heels       discount heels
..        ...                  ...
187  stiletto  best value stiletto
188  stiletto      offers stiletto
189  stiletto        sale stiletto
190  stiletto     bargain stiletto
191  stiletto  affordable stiletto

[192 rows x 2 columns]

## Create the match type column
<p>There are different keyword match types. One is exact match, which is for matching the exact term or are close variations of that exact term. Another match type is broad match, which means ads may show on searches that include misspellings, synonyms, related searches, and other relevant variations.</p>
<p>Straight from Google's AdWords <a href="https://support.google.com/google-ads/answer/2497836?hl=en">documentation</a>:</p>
<blockquote>
  <p>In general, the broader the match type, the more traffic potential that keyword will have, since your ads may be triggered more often. Conversely, a narrower match type means that your ads may show less often—but when they do, they’re likely to be more related to someone’s search.</p>
</blockquote>
<p>Since the client is tight on budget, we want to make sure all the keywords are in exact match at the beginning.</p>

In [13]:
keywords_df['Campaign'] = 'bata'

In [14]:
keywords_df['Criterion Type'] = 'Exact'

In [15]:
keywords_phrase = keywords_df.copy()
keywords_phrase['Criterion Type']='Phrase'

In [16]:
keywords_phrase

     Ad Group              Keyword Campaign Criterion Type
0       heels            buy heels     bata         Phrase
1       heels          price heels     bata         Phrase
2       heels       purchase heels     bata         Phrase
3       heels           cost heels     bata         Phrase
4       heels       discount heels     bata         Phrase
..        ...                  ...      ...            ...
187  stiletto  best value stiletto     bata         Phrase
188  stiletto      offers stiletto     bata         Phrase
189  stiletto        sale stiletto     bata         Phrase
190  stiletto     bargain stiletto     bata         Phrase
191  stiletto  affordable stiletto     bata         Phrase

[192 rows x 4 columns]

## The keywords into 'phrase' match
The great thing about exact match is that it is very specific, and we can control the process very well. The tradeoff, however, is that:

The search volume for exact match is lower than other match types
We can't possibly think of all the ways in which people search, and so, we are probably missing out on some high-quality keywords.
So it's good to use another match called phrase match as a discovery mechanism to allow our ads to be triggered by keywords that include our exact match keywords, together with anything before (or after) them.

Later on, when we launch the campaign, we can explore with modified broad match, broad match, and negative match types, for better visibility and control of our campaigns.

In [17]:
keywords_df_final = keywords_df.append(keywords_phrase)

In [21]:
keywords_df_final

     Ad Group              Keyword Campaign Criterion Type
0       heels            buy heels     bata          Exact
1       heels          price heels     bata          Exact
2       heels       purchase heels     bata          Exact
3       heels           cost heels     bata          Exact
4       heels       discount heels     bata          Exact
..        ...                  ...      ...            ...
187  stiletto  best value stiletto     bata         Phrase
188  stiletto      offers stiletto     bata         Phrase
189  stiletto        sale stiletto     bata         Phrase
190  stiletto     bargain stiletto     bata         Phrase
191  stiletto  affordable stiletto     bata         Phrase

[384 rows x 4 columns]

In [36]:
keywords_df_final.to_csv('keywords.csv',index=False)